---
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: multiarch
      labels:
        app: multiarch
    spec:
      replicas: 5
      selector:
        matchLabels:
          app: multiarch
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 50%
          maxSurge: 1
      template:
        metadata:
          labels:
            app: multiarch
          annotations:
            realtime: "true"
            rt_runtime_us: "50000"
        spec:
          containers:
          - name: multiarch
            image: fir.love.io:3005/multiarch:latest
            imagePullPolicy: Always

