---
platform: linux
image_resource:
  type: registry-image
  source: { repository: fir.love.io:3005/amd64/multiarch-gcc1321 }

inputs:
- name: cpp-multiarch-git

outputs:
- name: cpp-multiarch-git
      
run:
  path: ./cpp-multiarch-git/build.sh
  args: [ "--concourse", "--archlist=x86_64,aarch64", "--toolchain=../ArmLinux.cmake" ]   